name: Build and Release
on:
  push:
    tags:
      - 'v*' # Trigger on tags like 'v1.0.0'

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0' # or your flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Run flutter launcher icons
        run: flutter pub run flutter_launcher_icons

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/upload-keystore.jks

      - name: Build APK
        run: |
          flutter build apk --obfuscate --release --split-per-abi --build-number=$(git rev-list --count HEAD) --split-debug-info=build/app/outputs/symbols
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk
          
      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app-arm64-v8a-release.apk
            app-armeabi-v7a-release.apk
            app-x86_64-release.apk
          generate_release_notes: true
